name: w3c_event_source
version: 1.2.2
description: W3C EventSource client implementation for Dart / Flutter,
  to communicate with server-sent event endpoints.
author: Ren√©e Kooi <renee@kooi.me>
homepage: https://github.com/goto-bus-stop/dart-event-source

environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: any
